update wiki
luc-github/ESP8266 pull request #768
Opened 2022-05-28 13:48 UTC by atsju

group all printers and ESP32 to one page for easier maintenance.

mention #737

- [ ] group printers
- [ ] group ESP
- [ ] remove file about last modif date
- [ ] update sidePanel
- [ ] update building (V2/V3 arduino/platformIO) => separate PR
- [ ] update readme => separate PR

2022-05-28 13:48 UTC, atsju commented
@luc-github what do you think about this ?

2022-05-28 13:57 UTC, atsju commented
@luc-github could you also explain why CI is not passing when build comes from me ?
The purpose of CI is to check the main branch is working but it's also to check the PR **before** introducing a breaking change into main branch.

2022-05-28 14:19 UTC, atsju commented
@luc-github  what do you think of using format 
`<img src='https://raw.githubusercontent.com/wiki/luc-github/ESP3D/images/BIQU-KFB2.0/board.jpg' width='200'>` to have smaller but clickable pictures ?
<img src='https://raw.githubusercontent.com/wiki/luc-github/ESP3D/images/BIQU-KFB2.0/board.jpg' width='200'>

2022-05-28 14:21 UTC, luc-github commented
it is because it look for some url for the discord bot - and this URL is my secret variables - I am guessing because you do the PR the ci look for this variable in your fork and cannot find it - I need to check syntax how to check if variable exists to workaround because for PR submission there is not need of pushing to discord bot

2022-05-28 14:24 UTC, luc-github commented
IMHO smaller pictures are ok but you need to add text to each one  `click to enlarge` or people will not see them

2022-05-28 14:26 UTC, luc-github commented
>@luc-github what do you think about this ?

I am ok for it - you do lot !!! thank you

2022-05-28 14:27 UTC, atsju commented
> IMHO smaller pictures are ok but you need to add text to each one `click to enlarge` or people will not see them

of course 
https://www.youtube.com/watch?v=LE0aehh52xU

2022-05-28 14:44 UTC, luc-github commented
PR-workaround implemented - now it is show as passed

2022-05-28 15:34 UTC, atsju commented
@luc-github ready for review. The rest will be done in separate PRs
direct link for visualisation of the new page : https://github.com/atsju/ESP3D/blob/JST/wikiUpdate/wiki/hardware-connection.md

Thank you for your support and fast answers

2022-05-29 01:28 UTC, luc-github requested changes
Please see my comments : 
just 2 main topic
* tolerance to 5 V 
ESP8266 vs ESP32 and I would add also a disclamer as `this wiki is for reference - you are responsible of your board support or not 5V, we are not responsible for any damage of wrong wiring`

* confusion ESP**32** vs ESP**3D** vs ESP **boards** ?

Great job anyway

2022-05-29 01:28 UTC, luc-github commented on wiki/hardware-connection.md
> +## ESP32 board
Should be `ESP boards` instead I think

2022-05-29 01:28 UTC, luc-github commented on wiki/hardware-connection.md
> +
If you add this message - you should also unlike esp8266 ESP32 is not tolerant at all, because you refere to `ESP rx pin`  instead of `ESP8266 rx pin`

2022-05-29 01:28 UTC, luc-github commented on wiki/hardware-connection.md
> +If your motherboard doesn't support wifi, this repo will help you add an ESP32 board with an ESP8266 MCU. The ESP32 board supports wifi and will connect to your printer using a serial UART port thus
`this repo will help you add an ESP32 board with an ESP8266 MCU` I am not sure of the meaning of this, do you mean `ESP3D`  ?

2022-05-29 01:28 UTC, luc-github commented on wiki/hardware-connection.md
> +If your motherboard doesn't support wifi, this repo will help you add an ESP32 board with an ESP8266 MCU. The ESP32 board supports wifi and will connect to your printer using a serial UART port thus
same for `UART port that will be used with ESP32 board` do you mean ESP board ?

2022-05-29 07:21 UTC, atsju commented on wiki/hardware-connection.md
> +
shit, I though ESP32 was series of ESP8266 and simply named ESP32 boards containing ESP8266 chips. Now I see it's 2 different MCUs. Thanks

2022-05-29 07:29 UTC, luc-github commented on wiki/hardware-connection.md
> +
FYR ESP32 has several MCU also:
* ESP32 (supported by ESP3D)
* ESP32 -C2 (never tested this one)
* ESP32-C3(supported by ESP3D)
* ESP32-S2(supported by ESP3D)
* ESP32-S3 (supported by ESP3D)
* ESP32-H2 (not yet released)

2022-05-29 07:36 UTC, atsju commented on wiki/hardware-connection.md
> +
Also note ESP32 seem tolerant also (said the CEO) : https://www.ridiculously-simple.com/2021/05/19/are-the-esp32-and-esp8266-5v-tolerant-yes-they-officially-are/

2022-05-29 07:45 UTC, luc-github commented on wiki/hardware-connection.md
> +
Well do not rely on ceo wording, rely on spec sheets and experiment, esp32 does not handle 5v for sure,
I distroyed one board already, and even now on newest chips communication pins using 5v are not usable, so tolerance is may limited to damage but not communication which can be confusing to explain.
I really prefere not rely on FB post vs specs sheets, especially when I myself experiment the 5v non tolerance

2022-05-29 07:49 UTC, atsju commented on wiki/hardware-connection.md
> +
their spec sheets are shitty so I have to make some suppositions. 
Just to be sure, did you fry your board by applying 5V to an I/O that was already programmed as input ? (that would be 100% opposite to CEO sayings). I could understand if it fried programmed differently.

2022-05-29 08:18 UTC, luc-github commented on wiki/hardware-connection.md
> +
yes

2022-05-29 08:19 UTC, atsju commented on wiki/hardware-connection.md
> +
I own an ESP32CAM (ESP32-S) I didn't start until now. I will try this kind of test https://ba0sh1.com/2016/08/03/is-esp8266-io-really-5v-tolerant/ and try by myself. If it draws limited current at 5V it's definitely safe. Maybe I find some time at work this week

2022-05-29 08:21 UTC, atsju commented on wiki/hardware-connection.md
> +
I answered before seeing your yes. I will do the test to see if putting a serial resistor is OK (classic clamp diodes) of if a divider bridge or level shiffter is recommended

2022-05-29 08:33 UTC, luc-github commented on wiki/hardware-connection.md
> +
There are so different quality of boards (ESP8266/ESP32) that IMHO it is hard to say which one will be tolerant or not to damage
the key point is for me is  : `RX communication will not work for sure at 5V pin level` - the data will be corrupted

2022-05-29 08:39 UTC, atsju commented on wiki/hardware-connection.md
> +
Rx from which side ? Tx MCU Rx ESP will be corrupted ? This is unexpected but perfectly possible as we do not respect datasheet. It would confirm that the pin is 5V "tolerant" (i.e. not breaking) but that the chip isn't designed for it. Then I will likelly update propose a common solution for all chips (maybe divider bridge is easiest even if not perfect).

2022-06-02 02:33 UTC, luc-github commented on wiki/hardware-connection.md
> +
Yes ESP RX -  but for for most of people `tolerant` means it is will work ...

2022-06-02 05:17 UTC, atsju commented on wiki/hardware-connection.md
> +
What do you mean? I think I completely removed this part. I do not recommenf anymore anything border line

2022-06-02 05:19 UTC, luc-github commented on wiki/hardware-connection.md
> +
I just answered as I seems I did not looking at it - if not valid anymore it is fine ^_^

2022-06-04 09:22 UTC, atsju commented
@luc-github I may do the rest of tasks in separate PRs. Feel free to merge or to make additional comments

2022-06-04 11:11 UTC, luc-github approved these changes

2022-06-04 11:12 UTC, merged

2022-06-04 11:12 UTC, luc-github commented
Looks good for me - thank you